baseURL = 'https://polite-dragon-48bbbd.netlify.app'
languageCode = 'en-us'
title = "Danielle's Happy Place"
theme = 'digitalgarden'


[menu]
[[menu.main]]
  name = 'Home'
  url = '/'
  weight = 1
[[menu.main]]
  name = 'Content'
  [menu.main.params]
    header = true
  weight = 2
[[menu.main]]
  name = 'Articles'
  url = '/articles'
  weight = 3


[[menu.social]]
  name = 'Twitter'
  url = 'https://twitter.com'
  weight = 1
[[menu.social]]
  name = 'Instagram'
  url = 'https://instagram.com'
  weight = 2
[[menu.social]]
  name = 'GitHub'
  url = 'https://github.com/tdgao/hugo-blog'
  weight = 4
[[menu.social]]
  name = 'RSS'
  url = '/articles/index.xml'
  weight = 5


# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
  [markup.goldmark.renderer]
    # Enable to include inline HTML
    unsafe = true
