name: 'Deploy Notion Pages'

on:
  push:
    tags:
      - 'motion-link-*'

jobs:
  deploy:
    name: 'Pull from Notion and Push to Repo'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Remove old files
        run: git rm content/* && mkdir content
      - name: Pull Notion pages
        run: npm ci && npx motionlink ${{ secrets.MOTION_LINK_VARS }}
      - name: Commit changes
        run: |
          git config --global user.name 'Truman'
          git config --global user.email 'tdgao@users.noreply.github.com'
          git add .
          git commit -am "Sync Notion Pages"
          # Check if there are changes to push
          if [[ -z $(git status --porcelain) ]]; then
            echo "No changes to push"
          else
              git push origin HEAD:main
          fi